### ISSUE TITLE
Suggest build a website and/or pdf with Asciidoctor

### ISSUE THREAD

**Issue by eddiejaoude** [HarshKapadia2/git_basics#2]
If/when files are split out info sections, then Asciidoctor can be used to build a website and/or PDF and can also deploy to GitHub Pages

**Comment by HarshKapadia2** [comment]
The website has been hosted at https://harshkapadia2.github.io/git_basics/ using Asciidoctor 😄 
Thank you for all your help, @eddiejaoude !
