### ISSUE TITLE
Best practices for links.

### ISSUE THREAD

**Issue by HarshKapadia2** [HarshKapadia2/git_basics#23]
- [ ] Correct hyperlinks with text as 'here' or 'this' with meaningful text. (Might have to change the structure of sentence, obviously keeping the meaning and tense the same.)
Eg:
   - [This]() is the official documentation. ❌ 
   - [Official documentation]() ✔️ 

- [ ] Remove hyperlinks on pictures.

**Comment by Riya-code** [comment]
I would like to take it

**Comment by HarshKapadia2** [comment]
Go ahead @Riya-code. Please remember to follow the instructions in the [`CONTRIBUTING.md`](https://github.com/HarshKapadia2/git_basics/blob/master/CONTRIBUTING.md) file.

**Comment by Riya-code** [comment]
I think I might take a longer time. You can assign it to someone else :)

**Comment by HarshKapadia2** [comment]
Okay. Let me know if you want to do it and I'll re-assign you if someone else hasn't already taken it.

**Comment by Riya-code** [comment]
ok.Thanks.

**Comment by HirushaR** [comment]
I would like to take it

**Comment by Rodrigue819** [comment]
I tought I was going in to give a hand, but I think I did all of them. PR is open!

**Comment by HarshKapadia2** [comment]
The PRs for this issue are #46 and #49.
