### ISSUE TITLE
Add line in `git push` sub-section.

### ISSUE THREAD

**Issue by HarshKapadia2** [HarshKapadia2/git_basics#25]
- Add a line at the **end** of the `git push` sub-section in the `Commands` section.
- File path: `./src/commands/git_push.adoc`
- Syntax: `'''` (Please leave a blank line above this line.)

A line like the one below will be created, indicating the end of the sub-section.

---

**Comment by Finbob12** [comment]
Hi, Can I take this one?

**Comment by HarshKapadia2** [comment]
Go ahead @Finbob12!

> NOTE: Please do go through the `CONTRIBUTING.md` file for instructions to build the project before submitting a PR.
