### ISSUE TITLE
All external links should open in a new tab.

### ISSUE THREAD

**Issue by HarshKapadia2** [HarshKapadia2/git_basics#28]
> NOTE: Tackle this after issue #23.

- Currently, all external links (ie, links leading to web sites away from the git_basics web site itself) open in the same tab as the web site.
- All the external links should open in a separate tab.
- Implement the first method listed in the '[Links with attributes](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#:~:text=Link%20with%20attributes)' sub-section of the Asciidoctor Syntax Reference.

**Comment by Mu-C00L** [comment]
I want to work on this issue

**Comment by HarshKapadia2** [comment]
Hey @Mu-C00L, this issue requires issue #23 to be completed first. Could you handle that and then tackle this issue?

**Comment by HirushaR** [comment]
I would like to take it

**Comment by Mu-C00L** [comment]
> I would like to take it

I am working on it will soon do a PR.

**Comment by HirushaR** [comment]
ok but i did a PR

**Comment by Mu-C00L** [comment]
ok no problem
