### ISSUE TITLE
Add meta tags to the web site

### ISSUE THREAD

**Issue by HarshKapadia2** [HarshKapadia2/git_basics#30]
- The meta tags will have to be inserted by adding them **in the head** of a [Docinfo file](https://asciidoctor.org/docs/user-manual/#docinfo-file).
- The meta tags to be inserted

```html
<meta name="keywords" content="git, github, git_basics, git bash, basics of git, basics of github">
<meta name="description" content="A web site for the basics of Git and GitHub!">
```

**Comment by shivam7374** [comment]
@HarshKapadia2 I want to work on this. Please assign me this Issue.

**Comment by HarshKapadia2** [comment]
Solved!
