### ISSUE TITLE
Slightly misleading statement on hashing and compression

### ISSUE THREAD

**Issue by aidanhs** [HarshKapadia2/git_basics#36]
https://harshkapadia2.github.io/git_basics/ says

> Git actually compresses files with the zlib library and then hashes them

Which implied when I read it that a git hash is `sha1(zlib_compress(data))`.

However, the note a few paragraphs down corrects my misunderstanding:

> If blob 16\0Git is amazing! is hashed using SHA1, the same hash (1a3851c172420a2198cf8ca6f2b776589d955cc5) will be generated! 

Perhaps changing the original statement to something like "Git actually compresses files with the zlib library after hashing them"

**Comment by HarshKapadia2** [comment]
Thank you for raising this issue, @aidanhs!
Handled in commit 99426a03c3e18c4a5f1749f7eadf22d4e7d65bd5. Sorry for the delay!
Have a look: https://harshkapadia2.github.io/git_basics/#_the_blob_object
LMK if you feel that there need to be any more improvements.

**Comment by aidanhs** [comment]
Looks good!
