### ISSUE TITLE
To be added to the `resources` section.

### ISSUE THREAD

**Issue by HarshKapadia2** [HarshKapadia2/git_basics#58]
To the [resources section](https://harshkapadia2.github.io/git_basics/#_resources), add the following

- [x] [`Refined GitHub` browser extension](https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf)
- [x] [`GitZip for github` browser extension](https://chrome.google.com/webstore/detail/gitzip-for-github/ffabmkklhbepgcgfonabamgnfafbdlkn)
- [x] https://try.github.io

> NOTE:
> - Add the first two points under a new sub-heading called `Browser extensions for GitHub`.
> - Add the third point under the existing `Git Documentation` sub-heading.
> - Add all points as links that open in external tabs.

**Comment by crmsnbleyd** [comment]
Hello, I'd like to help with this issue!
