### ISSUE TITLE
Correct `alt` attribute of images

### ISSUE THREAD

**Issue by HarshKapadia2** [HarshKapadia2/git_basics#66]
- The alt tags of images are wrong at quite a few places.
- The image sizes have been taken as the `alt` attribute values at quite a few places. Correct the image size and add an `alt` attribute.
- Syntax: `image::file_name.ext[..., alt="value"]`
- [Asciidoctor image syntax documentation](https://docs.asciidoctor.org/asciidoc/latest/macros/images/)

**Comment by mtwn105** [comment]
Hi @HarshKapadia2, 

I would like to work on this issue.

Please can you assign it to me if no one else is working on this one.

**Comment by mtwn105** [comment]
Hi @HarshKapadia2 

Opened the PR #67

**Comment by HarshKapadia2** [comment]
Solved in PR #67.
