### ISSUE TITLE
Add 'Push Empty Git Commits'

### ISSUE THREAD

**Issue by tusharnankani** [HarshKapadia2/git_basics#85]
`git commit --allow-empty -m "Empty commit"`

It's like pushing a normal commit, except that you add the `--allow-empty` flag.

Reference: https://catalins.tech/git-empty-commit

**Comment by MahmoudDawood** [comment]
Sorry I don't get it, is the push empty git commit command not working?

**Comment by HarshKapadia2** [comment]
No, this is an issue to add the empty commit option to the [`git commit` command options](https://harshkapadia2.github.io/git_basics/#_optionsflags_7) in git_basics.

**Comment by MahmoudDawood** [comment]
I've tried to solve the issue as my first one ever and made a pull request, Could you review it and tell me if all is good?
